FactionIdentity : "{70417D0A46F9A67A}Configs/Identities/FactionIdentity_PERSIA.conf" {
 SocialIdentity SocialIdentity "{6960D7F2DB92CB73}" {
  NamesConfig {
   "Ali"
   "Hussain"
   "Hassan"
   "Abbas"
   "Omar"
   "Othman"
   "Abu"
   "Mohammed"
   "Ahmed"
   "Mustafa"
   "Mahmood"
   "Abdul"
   "Rahman"
   "Sattar"
   "Khalid"
   "Bilal"
   "Bashir"
   "Tariq"
   "Falah"
   "Mostafa"
   "Alaa"
   "Abdullah"
   "Saad"
  }
  SurnamesConfig {
   "Moslawi"
   "Basrawi"
   "Khafaji"
   "Yasiri"
   "Badry"
   "Haddad"
   "Najjar"
   "Sabbagh"
   "Khabbaz"
   "Sarraf"
   "Al-Baghdadi"
   "Al-Hashimi"
   "Al-Tikriti"
   "Al-Bayat"
   "Al-Hilli"
   "Kazem"
   "Mahdi"
   "Hamid"
   "Gabr"
   "Jawad"
   "Rashid"
   "Obaid"
   "Aboud"
  }
 }
}