FactionIdentity : "{70417D0A46F9A67A}Configs/Identities/FactionIdentity_PERSIA.conf" {
 SocialIdentity SocialIdentity "{6960D7F2AA91E970}" {
  NamesConfig {
   "Nabi"
   "Ghafoor"
   "Shah"
   "Madad"
   "Khan"
   "Nasim"
   "Sharif"
   "Sakhi"
   "Zaman"
   "Qadir"
   "Waleed"
   "Hazrat"
  }
  SurnamesConfig {
   "Mohammad"
   "Abdul"
   "Jangi"
   "Ali"
   "Ahmad"
   "Mohammad"
   "Akhtar"
   "Mohammad"
   "Gholam"
   "Abdul"
   "Ghulam"
   "Rahim"
  }
 }
}