SCR_FactionHomeTerritoryConfig {
 m_aFactionHomeTerritories {
  SCR_FactionHomeTerritory "{6960D7F342E8E025}" {
   m_sID "Al-Anbar"
   m_UIInfo SCR_UIInfo "{6960D7F342E8E02A}" {
    Name "Al-Anbar"
   }
   m_iWeight 18
  }
  SCR_FactionHomeTerritory "{6960D7F3F3B11757}" {
   m_sID "Babil"
   m_UIInfo SCR_UIInfo "{6960D7F0EE5183A3}" {
    Name "Babil"
   }
   m_iWeight 21
  }
  SCR_FactionHomeTerritory "{6960D7F3F0762608}" {
   m_sID "Baghdad"
   m_UIInfo SCR_UIInfo "{6960D7F0E93D90EE}" {
    Name "Baghdad"
   }
   m_iWeight 3
  }
  SCR_FactionHomeTerritory "{6960D7F3F0568421}" {
   m_sID "Basra"
   m_UIInfo SCR_UIInfo "{6960D7F0EB9BEE3F}" {
    Name "Basra"
   }
  }
  SCR_FactionHomeTerritory "{6960D7F3F0291D0C}" {
   m_sID "Dhi Qar"
   m_UIInfo SCR_UIInfo "{6960D7F0EB52CCC5}" {
    Name "Dhi Qar"
   }
   m_iWeight 21
  }
  SCR_FactionHomeTerritory "{6960D7F3F003906D}" {
   m_sID "Al-Qadisiyyah"
   m_UIInfo SCR_UIInfo "{6960D7F0EA053C83}" {
    Name "Al-Qadisiyyah"
   }
   m_iWeight 13
  }
  SCR_FactionHomeTerritory "{6960D7F3F0E47592}" {
   m_sID "Diyala"
   m_UIInfo SCR_UIInfo "{6960D7F0E510417D}" {
    Name "Diyala"
   }
   m_iWeight 16
  }
  SCR_FactionHomeTerritory "{6960D7F3F0FE71BB}" {
   m_sID "Duhok"
   m_UIInfo SCR_UIInfo "{6960D7F0E191A9D1}" {
    Name "Duhok"
   }
   m_iWeight 13
  }
  SCR_FactionHomeTerritory "{6960D7F3F0DDE22F}" {
   m_sID "Arbil"
   m_UIInfo SCR_UIInfo "{6960D7F0E090B3E7}" {
    Name "Arbil"
   }
   m_iWeight 19
  }
  SCR_FactionHomeTerritory "{6960D7F3F0B34D9C}" {
   m_sID "Karbala"
   m_UIInfo SCR_UIInfo "{6960D7F0E3D1E47B}" {
    Name "Karbala"
   }
   m_iWeight 12
  }
  SCR_FactionHomeTerritory "{6960D7F3D5097083}" {
   m_sID "Kirkuk"
   m_UIInfo SCR_UIInfo "{6960D7F0E2BCD72F}" {
    Name "Kirkuk"
   }
   m_iWeight 16
  }
  SCR_FactionHomeTerritory "{6960D7F3D5E06F51}" {
   m_sID "Maysan"
   m_UIInfo SCR_UIInfo "{6960D7F09DA66771}" {
    Name "Maysan"
   }
   m_iWeight 11
  }
  SCR_FactionHomeTerritory "{6960D7F3D5C5A9FF}" {
   m_sID "Muthanna"
   m_UIInfo SCR_UIInfo "{6960D7F09CBC5869}" {
    Name "Muthanna"
   }
   m_iWeight 8
  }
  SCR_FactionHomeTerritory "{6960D7F3D5DE8F01}" {
   m_sID "Najaf"
   m_UIInfo SCR_UIInfo "{6960D7F09FF7C3A4}" {
    Name "Najaf"
   }
   m_iWeight 15
  }
  SCR_FactionHomeTerritory "{6960D7F3D5B29D82}" {
   m_sID "Nineveh"
   m_UIInfo SCR_UIInfo "{6960D7F09EA31B04}" {
    Name "Nineveh"
   }
   m_iWeight 37
  }
  SCR_FactionHomeTerritory "{6960D7F3D597B6ED}" {
   m_sID "Salah Al-Din"
   m_UIInfo SCR_UIInfo "{6960D7F099EFE0C8}" {
    Name "Salah Al-Din"
   }
   m_iWeight 16
  }
  SCR_FactionHomeTerritory "{6960D7F3DA6E7303}" {
   m_sID "Sulaymaniyah"
   m_UIInfo SCR_UIInfo "{6960D7F098C204F5}" {
    Name "Sulaymaniyah"
   }
   m_iWeight 22
  }
  SCR_FactionHomeTerritory "{6960D7F3DA410BAA}" {
   m_sID "Wasit"
   m_UIInfo SCR_UIInfo "{6960D7F09BD4FFC3}" {
    Name "Wasit"
   }
   m_iWeight 14
  }
 }
 m_fSharedPlaceOfBirthWeight 0.5
}