SCR_Faction : "{277AE7613D88A55B}Configs/Factions/INDFOR.conf" {
 FactionKey "GC_MUJ"
 FactionColor 0 0.502 0.1255 1
 UIInfo SCR_FactionUIInfo "{670CF087CE37FA75}" {
  Name "Mujahideen"
  Icon "{5E4DDEE56C6D4D16}Images/GC_MUJ_icon.edds"
  m_sNameUpper "MUJAHIDEEN"
 }
 "Identity of soldiers" FactionIdentity "{6960D7F29A7CB7FC}" : "{024218D2C7AFC638}Configs/Identities/FactionIdentity_Afghan.conf" {
 }
 "Radio encryption key" "GC_MUJ"
 m_iOrder 2005
 m_OutlineFactionColor 0 0.322 0.08 1
 m_NotificationFactionColor 0 0.502 0.125 1
 m_NotificationTextFactionColor 0 0.502 0.125 1
 m_bIsPlayable 0
 m_bShowInWelcomeScreenIfNonPlayable 0
 m_sFactionFlag "{5E4DDEE56C6D4D16}Images/GC_MUJ_icon.edds"
 m_FactionFlagMaterial "{B7A02313829700F9}Assets/Props/Fabric/Flags/Data/Flag_1_2_Green.emat"
 m_FactionLabel FACTION_GC_MUJ
 m_aFriendlyFactionsIds {
  "CIV"
 }
 m_CallsignInfo SCR_FactionCallsignInfo "{60A6B21E18F28741}" : "{D7164359D005B37A}Configs/Callsigns/Callsigns_FIA.conf" {
 }
 m_iFactionRadioFrequency 52000
 m_sGroupFlagsImageSet "{7CD99D22C7AE8195}UI/Textures/GroupManagement/FlagIcons/GroupFlagsOpfor.imageset"
 m_sGroupFlagsImageSetOutlines "{B9356E7B2E974DCD}UI/Textures/GroupManagement/FlagIcons/GroupFlagsOpfor-outline.imageset"
 m_rMapPrefab "{F849217AB3BA88BE}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded_USSR.et"
}